Traceback (most recent call last):
  File "test-data-2.0/extras/testWrongKeywordArg2.py", line 8, in <module>
    p = Point(foo=3, y=4)

WyppTypeError: unbekanntes Schl√ºsselwort-Argument

Konstruktor des Records `Point` akzeptiert kein Schl√ºsselwort-Argument `foo`.

## Datei test-data-2.0/extras/testWrongKeywordArg2.py
## Fehlerhafter Aufruf in Zeile 8:

p = [0;31m[1mPoint(foo=3, y=4)[0;0m