Traceback (most recent call last):
  File "test-data-2.0/basics/forwardRefs.py", line 12, in <module>
    a.foo(a)

WyppTypeError: <__wypp__.A object at 0x00>

Der Aufruf der Methode `foo` aus Klasse `A` erwartet Wert vom Typ `B` als erstes Argument.
Aber der Ã¼bergebene Wert hat Typ `A`.

## Datei test-data-2.0/basics/forwardRefs.py
## Fehlerhafter Aufruf in Zeile 12:

a.foo(a)

## Typ deklariert in Zeile 4:

    def foo(self, [0;31m[1mb: B[0;0m):