Traceback (most recent call last):
  File "", line 5, in <module>
    foo([1, 2, 3])
  File "", line 3, in foo
    return l

WyppTypeError: [1, 2, 3, '4']

RÃ¼ckgabewert vom Typ `list[int]` erwartet bei Aufruf der Funktion `foo`.

## Datei listResult.py
## RÃ¼ckgabetyp deklariert in Zeile 1:

def foo(l: list[int]) -> [0;31m[1mlist[int][0;0m:

## Fehlerhaftes return in Zeile 3:

    return l

## Aufruf in Zeile 5 verursacht das fehlerhafte return:

foo([1, 2, 3])
